### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by shijunil** [mnestis/nlgserv#2]
Sorry but I m new to python coding. Can you pls explain me how to use this wraper for simpleNLG. I want to generate new sentences using SVO(subject verb object) triples.
Thanks

**Comment by terbo** [comment]
Once you've installed nlgserv, run nlgserv [ip] [port] for the server.
This, however, doesn't work for me (I'm on Kali 2) so I just go to
the source directory and execute 

./jython.jar _server.py [ip] [port]

Then you an go to the nlgserv/tests/fixtures directory and read the
format of the JSON files. You can test the files by running this:

cat cake.json | POST -c application/json http://[ip]:[port]/generateSentence

Might something like this be included in the readme?
I'm going to investigate why simply running nlgserv doesn't work..

**Comment by mnestis** [comment]
Sorry @shijunil, your post must have gotten lost in the flood of email. 

I must admit I wasn't expecting it to generate this level of interest. Thanks for the feedback @terbo. When I get a chance, I'll tidy things up a bit, add some documentation, and test on a few different build environments.

**Comment by mnestis** [comment]
Also, to generate SVO, you would send it JSON similar to:

 {"sentence": {
     "subject": "John",
     "verb": "bake",
     "object": "cake"
 }}

Things get a bit more complicated if you want to take about plural things.
