### ISSUE TITLE
Test on different environments

### ISSUE THREAD

**Issue by mnestis** [mnestis/nlgserv#4]
At moment, only tested on two, very similar environments.

**Comment by Abhishek-P** [comment]
Hey I am running it on Ubuntu 15.04 in VM , This is the error i am getting when i try nlgserv.start_server("host",1729)
Starting nlgserv on host:1729
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/nlgserv-0.2.3-py2.7.egg/nlgserv/_controller.py", line 25, in start_server
    preexec_fn=os.setsid)
  File "subprocess.py", line 710, in __init__
    errread, errwrite)
  File "subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied

**Comment by mnestis** [comment]
Hi @Abhishek-P,

This was something I cobbled together to act as part of my PhD project. Consequently, I don't really have time to maintain it or fix bugs, as it suits the purposes I need it for.

Feel free to take the code and try and fix it, but I'm afraid I can't really help you. If you are able to use the Java library directly, I'd really recommend you do that instead.

Thanks,
Darren..
